"""Creating tables

Revision ID: 351d69537080
Revises: 
Create Date: 2021-05-13 13:29:50.734958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351d69537080'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppies')
    # ### end Alembic commands ###
